# Generated by Django 5.0.3 on 2024-03-26 10:28

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0003_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='data_modified',
        ),
        migrations.AddField(
            model_name='profile',
            name='Data_modified',
            field=models.DateTimeField(auto_now=True, verbose_name=django.contrib.auth.models.User),
        ),
    ]
