# Generated by Django 5.0.3 on 2024-03-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0004_remove_profile_data_modified_profile_data_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='old_cart',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
