# Generated by Django 5.0.3 on 2024-03-29 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0005_profile_old_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='passward',
            new_name='password',
        ),
    ]
